//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJ_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id { get; set; }
        public Nullable<int> passenger { get; set; }
        public Nullable<int> route { get; set; }
        public Nullable<int> board { get; set; }
        public Nullable<int> arrive { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual User User { get; set; }
        public virtual Route Route1 { get; set; }
    }
}
